ShopProject/Models/Cap.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShopProject.Models
{
    public class Cap : Product
    {
        [Key]
        [ScaffoldColumn(false)]
        public int CapId { get; set; }
    }
}

ShopProject/Controllers/BeltController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopProject.Models;
using ShopProject.ViewModel;
using ShopProject.BL;

namespace ShopProject.Controllers
{
    [Authorize]
    public class BeltController : Controller
    {
        // GET: Belt
        public ActionResult BeltList()
        {
            BeltListVM beltListVM = new BeltListVM();
            BeltBL beltBL = new BeltBL();
            List<Belt> beltList = new List<Belt>();
            beltListVM.BeltVMList = BeltList2BeltVMList(beltBL.GetBeltList());

            return View(beltListVM);
        }


        public ActionResult ShowPhotoBelt(int id)
        {
            return View();
        }


        public ActionResult AddBelt()
        {
            AddBeltVM addBeltVM = new AddBeltVM();
            return View(addBeltVM);
        }


        [HttpPost]
        public ActionResult AddBelt(Belt belt)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View("AddBelt", belt);
                }

                else
                {
                    BeltBL beltBL = new BeltBL();
                    HttpPostedFileBase file = Request.Files["imageFile"];
                    if (file != null && file.ContentLength > 0)
                    {
                        belt.ProductImage = file.FileName;
                        file.SaveAs(HttpContext.Server.MapPath("../Images/") + belt.ProductImage);
                    }

                    beltBL.AddBelt(belt);
                    return RedirectToAction("BeltList");
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return View();
            }
        }

        [HttpGet]
        public ActionResult EditBelt()
        {
            Belt belt = new Belt();
            return View();
        }


        [HttpPost]
        public ActionResult EditBelt(Belt belt)
        {
            
            try
            {
                BeltBL beltBL = new BeltBL();
                beltBL.EditBelt(belt.BeltId, belt.Name,belt.Cost,belt.Description);

                return RedirectToAction("BeltList");
            }
            catch
            {
                return View();
            }
        }


        //public ActionResult DeleteBelt()
        //{
            
        //    return View();
        //}


        //[HttpPost]
        public ActionResult DeleteBelt(Belt belt)
        {
            try
            {
                BeltBL beltBL = new BeltBL();
                beltBL.DeleteBelt(belt.BeltId);

                return RedirectToAction("BeltList");
            }
            catch
            {
                return View();
            }
        }



        private List<BeltVM> BeltList2BeltVMList(List<Belt> beltList)
        {
            List<BeltVM> BeltVMList = new List<BeltVM>();

            foreach (Belt belt in beltList)
            {
                BeltVM beltVM = new BeltVM();
                beltVM.belt = belt;
                BeltVMList.Add(beltVM);
            }

            return BeltVMList;
        }
    }
}

ShopProject/Controllers/CapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopProject.Models;
using ShopProject.ViewModel;
using ShopProject.BL;

namespace ShopProject.Controllers
{
    [Authorize]
    public class CapController : Controller
    {
        public ActionResult CapList()
        {
            CapListVM capListVM = new CapListVM();
            CapBL capBL = new CapBL();
            List<Cap> capList = new List<Cap>();
            capListVM.CapVMList = CapList2CapVMList(capBL.GetCapList());

            return View(capListVM);
        }


        public ActionResult ShowPhotoCap(int id)
        {
            return View();
        }


        public ActionResult AddCap()
        {
            AddCapVM addCapVM = new AddCapVM();
            return View(addCapVM);
        }


        [HttpPost]
        public ActionResult AddCap(Cap cap)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("AddCap", cap);
                }

                else
                {
                    CapBL capBL = new CapBL();
                    HttpPostedFileBase file = Request.Files["imageFile"];
                    if (file != null && file.ContentLength > 0)
                    {
                        cap.ProductImage = file.FileName;
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/") + cap.ProductImage);
                    }
                    capBL.AddCap(cap);
                    return RedirectToAction("CapList");
                }
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult EditCap()
        {
            Cap cap = new Cap();
            return View();
        }


        [HttpPost]
        public ActionResult EditCap(Cap cap)
        {

            try
            {
                CapBL capBL = new CapBL();
                capBL.EditCap(cap.CapId, cap.Name, cap.Cost, cap.Description);

                return RedirectToAction("CapList");
            }
            catch
            {
                return View();
            }
        }


        //public ActionResult DeleteCap()
        //{

        //    return View();
        //}


        //[HttpPost]
        public ActionResult DeleteCap(Cap cap)
        {
            try
            {
                CapBL capBL = new CapBL();
               
                capBL.DeleteCap(cap.CapId);

                return RedirectToAction("CapList");
            }
            catch
            {
                return View();
            }
        }



        private List<CapVM> CapList2CapVMList(List<Cap> capList)
        {
            List<CapVM> CapVMList = new List<CapVM>();

            foreach (Cap cap in capList)
            {
                CapVM capVM = new CapVM();
                capVM.cap = cap;
                CapVMList.Add(capVM);
            }

            return CapVMList;
        }




    }
}

ShopProject/Controllers/WatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopProject.Models;
using ShopProject.ViewModel;
using ShopProject.BL;

namespace ShopProject.Controllers
{
    [Authorize]
    public class WatchController : Controller
    {
        public ActionResult WatchList()
        {
            WatchListVM watchListVM = new WatchListVM();
            WatchBL watchBL = new WatchBL();
            List<Watch> watchList = new List<Watch>();
            watchListVM.WatchVMList = WatchList2WatchVMList(watchBL.GetWatchList());

            return View(watchListVM);
        }


        public ActionResult ShowPhotoWatch(int id)
        {
            return View();
        }


        public ActionResult AddWatch()
        {
            AddWatchVM addWatchVM = new AddWatchVM();
            return View(addWatchVM);
        }


        [HttpPost]
        public ActionResult AddWatch(Watch watch)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("AddWatch", watch);
                }

                else
                {
                    WatchBL watchBL = new WatchBL();
                    HttpPostedFileBase file = Request.Files["imageFile"];
                    if (file != null && file.ContentLength > 0)
                    {
                        watch.ProductImage = file.FileName;
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/") + watch.ProductImage);
                    }
                    watchBL.AddWatch(watch);
                    return RedirectToAction("WatchList");
                }
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult EditWatch()
        {
            Watch watch = new Watch();
            return View();
        }


        [HttpPost]
        public ActionResult EditWatch(Watch watch)
        {

            try
            {
                WatchBL watchBL = new WatchBL();
                watchBL.EditWatch(watch.WatchId, watch.Name, watch.Cost, watch.Description);

                return RedirectToAction("WatchList");
            }
            catch
            {
                return View();
            }
        }

        //public ActionResult DeleteWatch()
        //{

        //    return View();
        //}


        //[HttpPost]
        public ActionResult DeleteWatch(Watch watch)
        {
            try
            {
                WatchBL watchBL = new WatchBL();
                watchBL.DeleteWatch(watch.WatchId);

                return RedirectToAction("WatchList");
            }
            catch
            {
                return View();
            }
        }



        private List<WatchVM> WatchList2WatchVMList(List<Watch> watchList)
        {
            List<WatchVM> WatchVMList = new List<WatchVM>();

            foreach (Watch watch in watchList)
            {
                WatchVM watchVM = new WatchVM();
                watchVM.watch = watch;
                WatchVMList.Add(watchVM);
            }

            return WatchVMList;
        }
    }
}

ShopProject/Views/Cap/AddCap.cshtml
@model ShopProject.ViewModel.AddCapVM

@{
    ViewBag.Title = "AddCap";
}

<h2>Dodawanie Czapki</h2>

@using (Html.BeginForm("AddCap", "Cap", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<table>
    <tr>
        <td>@Html.DisplayNameFor(model => Model.cap.Name)</td>
        <td>@Html.EditorFor(model => Model.cap.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => Model.cap.Cost)</td>
        <td>@Html.EditorFor(model => Model.cap.Cost)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => Model.cap.Description)</td>
        <td>@Html.EditorFor(model => Model.cap.Description)</td>
    </tr>

    <tr>
        <td>
            <input type="file" name="imageFile" size="23" accept="gif|jpg|png" />
            @Html.ValidationMessageFor(model => model.cap.ProductImage)
        </td>
    </tr>
</table>


    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" class="btn btn-info" value="Powróć" onclick="location.href='@Url.Action("CapList", "Cap")'" /> <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ShopProject/Views/Cap/CapList.cshtml
@using ShopProject.ViewModel

@model CapListVM

@{
    ViewBag.Title = "CapList";
}




<div class="creator">
    <input type="button" class="btn btn-info" value="Dodaj Czapkę" onclick="location.href='@Url.Action("AddCap", "Cap")'" />
</div>
<div>
    <table>
        <tr>
            <th>@Html.DisplayNameFor(model => Model.CapVMList[0].cap.CapId)</th>
            <th>@Html.DisplayNameFor(model => Model.CapVMList[0].cap.Name)</th>
            <th>@Html.DisplayNameFor(model => Model.CapVMList[0].cap.Cost)</th>
            <th>@Html.DisplayNameFor(model => Model.CapVMList[0].cap.Description)</th>
            <th></th>
            <th></th>
        </tr>



        @foreach (CapVM item in Model.CapVMList)
        {
            <tr>
                <td>@item.cap.CapId</td>
                <td>@item.cap.Name</td>
                <td>@item.cap.Cost</td>
                <td>@item.cap.Description</td>
                <td>@Html.ActionLink("Edytuj", "EditCap", item.cap)</td>
                <td>@Html.ActionLink("Usuń", "DeleteCap", item.cap)</td>
            </tr>
        }

    </table>

    <div class="miniContainer">
        <div class="selectProductList" id="first">
            <input type="button" class="btn btn-info" value="Paski" onclick="location.href='@Url.Action("BeltList", "Belt")'" />
        </div>
        <div class="selectProductList">
            <input type="button" class="btn btn-info" value="Czapki" onclick="location.href='@Url.Action("CapList", "Cap")'" />
        </div>
        <div class="selectProductList">
            <input type="button" class="btn btn-info" value="Zegarki" onclick="location.href='@Url.Action("WatchList", "Watch")'" />
        </div>
    </div>
</div>

ShopProject/Views/Cap/DeleteCap.cshtml
@model ShopProject.ViewModel.DeleteCapVM

@{
    ViewBag.Title = "DeleteCap";
}

<h2>DeleteCap</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cap.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cap.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cap.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cap.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cap.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cap.Description)
        </dd>

    </dl>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShopProject/Views/Cap/EditCap.cshtml
@model ShopProject.Models.Cap

@{
    ViewBag.Title = "EditCap";
}

<h2>Edytuj Czapkę</h2>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>@Html.DisplayNameFor(model => Model.Name)</td>
            <td>@Html.EditorFor(model => Model.Name)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => Model.Cost)</td>
            <td>@Html.EditorFor(model => Model.Cost)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => Model.Description)</td>
            <td>@Html.EditorFor(model => Model.Description)</td>
        </tr>
    </table>
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" class="btn btn-info" value="Powróć" onclick="location.href='@Url.Action("CapList", "Cap")'" />  <input type="submit" value="Edytuj" class="btn btn-default" />
            </div>
        </div>
    </div>
}